# Generated by Django 3.2.8 on 2021-10-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=250)),
                ('Apellido', models.CharField(max_length=250)),
                ('Empresa', models.CharField(max_length=250)),
                ('Telefono', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
